//🧠 Conditional Statement kya hota hai?

//Conditional statement ka matlab hota hai: 👉 “Agar yeh hua, toh yeh karo… warna kuch aur karo”

// Jaise real life mein:

// Agar baarish ho rahi hai → umbrella le jao ☔
// Agar bhook lagi hai → khaana khao 🍔
// Agar homework complete hai → game khelo 🎮

//JavaScript mein conditional statements ke main 4–5 types hote hain.       


// 1. if statement - 👉 Sirf ek condition check karta hai
// 2. if...else - 👉 Do options deta hai (yes / no type)
// 3. if...else if...else - 👉 Multiple conditions check karta hai	
// 4. switch statement - 👉 Jab ek value ke multiple cases ho
// 5. Ternary Operator - 👉 Short form of if...else


    // 1. if statement 

    if (condition) {
  // code chalega agar condition true hai
}

// 2. if...else statement
if(condition){
    //agar true
} else {
    //agar false
}

//3. if..else if...else statement

if (condition1){
    //option 1 -
} else if(condition){
    // option 2 -
} else {
    //option 3 -
}

